### ISSUE TITLE
Duplicate declaration "i18nConfig" when using globalImport

### ISSUE THREAD

**Issue by luxcem** [skolmer/babel-plugin-i18n-tag-translate#6]
When using `globalImport: true` I get the following error:

```
error: bundling failed: TypeError: [redacted]/node_modules/es2015-i18n-tag/dist/lib/index.js: Duplicate declaration "i18nConfig"

    at File.buildCodeFrameError ([redacted]/node_modules/@babel/core/lib/transformation/file/file.js:261:12)
    at Scope.checkBlockScopedCollisions ([redacted]/node_modules/@babel/traverse/lib/scope/index.js:347:22)
    at Scope.registerBinding ([redacted]/node_modules/@babel/traverse/lib/scope/index.js:504:16)
    at Scope.registerDeclaration ([redacted]/node_modules/@babel/traverse/lib/scope/index.js:444:14)
    at Object.Declaration ([redacted]/node_modules/@babel/traverse/lib/scope/index.js:125:12)
    at NodePath._call ([redacted]/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call ([redacted]/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit ([redacted]/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue ([redacted]/node_modules/@babel/traverse/lib/context.js:118:16)
```

This also happen when setting `config` due to https://github.com/skolmer/babel-plugin-i18n-tag-translate/blob/master/src/index.js#L125.

**Comment by skolmer** [comment]
Do you somewhere import i18nConfig in your js modules? I don't think I implemented a duplication check when I wrote this.

**Comment by luxcem** [comment]
No, I think the duplication occur in es2015-i18n-tag/dist/lib/index.js file, I don't know why the babel transform try to process this file though my babel.config.js is 
```
[
            "i18n-tag-translate",
            {
                translation: path.join(__dirname, "translations", "en.json"),
                groupDir: path.join(__dirname, "src"),
                globalImport: true,
            },
        ],
```

**Comment by skolmer** [comment]
Strange, babel should ignore the node_modules directory by default.
